name: Deploy BLIN

on:
  push:
    branches: [ "main" ]

jobs:
  # Validamos que el código compile antes de tocar el servidor
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install & Build Test
        env:
          # Estas variables solo se usan aquí para que el build de GitHub no de error
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: |
          npm install
          npm run build

  # Despliegue al servidor
  deploy:
    needs: build-check
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.servidor_IP }}
          username: ${{ secrets.usuario_servidor }}
          key: ${{ secrets.key_privada_ssh }}
          script: |
            # 1. Entrar a la carpeta
            cd /home/adminuser/BLIN/BLIN/
            
            # 2. Actualizar código
            git pull origin main
            
            # 3. Instalar y Construir (Usará el .env que ya tienes en el servidor)
            npm install
            npm run build
            
            # 4. Reiniciar proceso en PM2 (Corregido)
            pm2 restart blin-app || pm2 start npm --name "blin-app" -- start